ServerTokens Full
ServerSignature On

<VirtualHost *:80>
    Header add Set-Cookie "sid=abc123; Path=/"
    Header add X-Powered-By "PHP/7.4.3"
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile    /usr/local/apache2/certs/server.crt
    SSLCertificateKeyFile /usr/local/apache2/certs/server.key
    SSLProtocol -all +TLSv1.2 +TLSv1.3
    Header add Set-Cookie "sid=abc123; Path=/"
    Header add X-Powered-By "PHP/7.4.3"
</VirtualHost>