ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
    Redirect permanent / https://localhost:9543/
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile    /usr/local/apache2/certs/server.crt
    SSLCertificateKeyFile /usr/local/apache2/certs/server.key
    SSLProtocol -all +TLSv1.2 +TLSv1.3

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set Content-Security-Policy "default-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'"
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
   
    Header always add Set-Cookie "__Host-sid=abc123; Path=/; Secure; HttpOnly; SameSite=Strict"
</VirtualHost>