server_tokens on;

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    add_header Set-Cookie "sid=abc123; Path=/";
    add_header X-Powered-By "PHP/7.4.3";
}

server {
    listen 443 ssl;
    server_name localhost;
    root /usr/share/nginx/html;
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    add_header Set-Cookie "sid=abc123; Path=/";
    add_header X-Powered-By "PHP/7.4.3";
}